'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('pils', [
      {
      title: "10 Actionable Tips for Increasing Your Website's Conversion Rate",
      text: "As a business owner, you want your website to be as effective as possible at converting visitors into customers. Here are 10 actionable tips for increasing your website's conversion rate:      Clearly define your target audience: Understand who your ideal customer is and create content that speaks directly to them. Make sure your website is mobile-friendly: With more and more people using their phones to browse the web, it's crucial that your website is easy to use on a small screen. Use social proof: Testimonials and customer reviews can go a long way in convincing someone to make a purchase. Use clear and compelling calls to action: Tell visitors exactly what you want them to do, whether it's to make a purchase or sign up for your email list. Simplify your website's design: A cluttered or confusing design can turn people away. Keep things simple and easy to navigate. Test different headlines and copy: A/B testing different versions of your website's headlines and copy can help you see what works best at converting visitors. Optimize your website for speed: No one likes a slow-loading website. Make sure your website loads quickly to keep people from bouncing. Make sure your website is secure: Use SSL to encrypt data and make sure your website is secure. This can increase trust and credibility with visitors. Use high-quality images: Visuals are important and can help convey your message and brand. Make sure you're using high-quality images on your website. Offer incentives: Consider offering incentives such as free shipping or a discount to encourage people to make a purchase. By following these tips, you can increase your website's conversion rate and turn more visitors into customers.",
      type: "ux, ui, conversion",
      img: "https://cdn.pixabay.com/photo/2019/06/25/08/17/cro-4297722__480.jpg",
      creation_date: "2022-11-11",
      userMail: "adminseeder@admin.com"
    },
    {
      title: "he Top 3 Ways to Use Social Media for Business Growth",
      text: "Social media has become an integral part of modern business, with almost every company utilizing it in some way to reach their target audience. However, simply having a presence on social media is not enough to see significant business growth. Here are the top three ways to use social media for business growth: Engage with your audience. One of the biggest benefits of social media is the ability to connect with your audience in real-time. By regularly posting updates, responding to comments and messages, and engaging with users, you can create a loyal customer base that will continue to support your business. Utilize paid advertising. While organic reach on social media can be limited, paid advertising allows you to target specific demographics and increase the visibility of your brand. By carefully crafting your ad campaigns and analyzing the results, you can effectively reach a larger audience and drive more traffic to your business. Collaborate with influencers. Partnering with influencers in your industry can be a powerful way to increase your reach and credibility. By working with influencers who already have a large following, you can tap into their audience and potentially gain new customers. Overall, social media is a valuable tool for business growth, but it requires a strategic approach to truly see results. By engaging with your audience, utilizing paid advertising, and collaborating with influencers, you can effectively leverage social media to drive business growth.",
      type: "sem, social, paid",
      img: "https://cdn.pixabay.com/photo/2014/03/22/22/17/phone-292994__480.jpg",
      creation_date: "2022-11-11",
      userMail: "adminseeder@admin.com"
    },
    {
      title: "The Importance of Customer Retention for Business Growth",
      text: "Customer retention is a crucial aspect of any business, as it plays a significant role in the growth and success of the company. When a business is able to retain its customers, it is able to generate more revenue and profits, which in turn allows for the business to expand and prosper. On the other hand, a business that fails to retain its customers is likely to struggle and may even face bankruptcy. There are several reasons why customer retention is so important for business growth. First and foremost, it is much cheaper to retain an existing customer than it is to acquire a new one. It costs significantly less to sell to an existing customer than to attract and convert a new one. This is because an existing customer is already familiar with the company, its products, and its services. They are also more likely to make repeat purchases, which can generate a steady stream of revenue for the business. In addition to the cost savings, customer retention also helps to build brand loyalty. When a customer has a positive experience with a company and continues to do business with them, they are more likely to recommend the company to their friends and family. This can lead to a ripple effect, as those recommendations can lead to new customers and further growth for the business. Furthermore, customer retention helps to create a stable customer base for the business. When a company has a high retention rate, it is able to rely on a consistent stream of revenue, rather than constantly having to attract and convert new customers. This stability allows the business to focus on long-term growth and planning, rather than constantly having to adapt to fluctuating customer numbers. In conclusion, customer retention is an essential aspect of business growth. It helps to reduce costs, build brand loyalty, and create a stable customer base. Companies that prioritize customer retention are likely to see significant growth and success in the long run.",
      type: "retention",
      img: "https://www.thealternativeboard.com/hubfs/Compressed-bigstock-Customer-Retention-Strategy-D-255195535.jpg",
      creation_date: "2022-11-11",
      userMail: "adminseeder@admin.com"
    },
    {
      title: "How to Use Content Marketing for Sustainable Business Growth",
      text: "Content marketing is a powerful tool for sustainable business growth. It is a strategic approach that focuses on creating and distributing valuable, relevant, and consistent content to attract and retain a clearly defined audience. By providing valuable information, businesses can attract customers and establish themselves as thought leaders in their industry. One of the key elements of content marketing is to understand your target audience. This involves researching and understanding their needs, wants, and challenges, and creating content that addresses these issues. It is important to create a content calendar that outlines the topics you will be covering and the frequency of your content distribution. Another important aspect of content marketing is the use of various channels to distribute your content. This can include social media, email marketing, and your website. It is important to have a presence on a variety of channels to reach as many potential customers as possible. Finally, it is important to measure and analyze the success of your content marketing efforts. This can be done through tools such as Google Analytics, which allows you to track website traffic and user behavior. By analyzing this data, you can identify areas for improvement and adjust your strategy accordingly. Overall, content marketing is a crucial aspect of sustainable business growth. By understanding your target audience, distributing content through various channels, and measuring and analyzing your efforts, you can effectively use content marketing to attract and retain customers and establish your business as a thought leader in your industry.",
      type: "content, seo, social",
      img: "https://cdn.pixabay.com/photo/2016/10/09/08/32/digital-marketing-1725340__480.jpg",
      creation_date: "2022-11-11",
      userMail: "adminseeder@admin.com"
    },
    {
      title: "How to Use Email Marketing to Drive Business Growth",
      text: "Email marketing is a powerful tool for businesses looking to drive growth and increase their customer base. By sending targeted emails to a specific group of people, businesses can effectively promote their products or services, generate leads, and build brand awareness. Here are some tips on how to use email marketing to drive business growth: Build a targeted email list. The first step to successful email marketing is to build a list of individuals who are interested in your products or services. This can be done through opt-in forms on your website, social media, or in-store sign-ups. It’s important to segment your email list based on factors such as demographics, location, and past purchases to ensure that you’re sending relevant content to the right people. Create engaging email campaigns. Once you have a targeted list, it’s time to create email campaigns that will grab your audience’s attention. This includes designing visually appealing emails with a clear call to action, crafting compelling subject lines, and using segmentation to send personalized emails to different groups of customers. It’s also important to test different elements of your emails, such as subject lines and email content, to see what works best for your audience. Measure and analyze results. To determine the effectiveness of your email marketing efforts, it’s crucial to track and analyze key metrics. This includes the open rate, click-through rate, and conversion rate of your emails. By analyzing this data, you can determine which emails are performing well and make adjustments to your campaigns accordingly. Use automation and integration. Email marketing automation allows you to schedule and send emails based on specific triggers, such as a customer’s birthday or the date they last made a purchase. By automating certain aspects of your email marketing, you can save time and focus on other areas of your business. Additionally, integrating your email marketing efforts with other marketing channels, such as social media and your website, can help to create a cohesive marketing strategy and drive even more business growth. In conclusion, email marketing is a powerful tool for driving business growth. By building a targeted email list, creating engaging campaigns, measuring and analyzing results, and using automation and integration, businesses can effectively promote their products or services and increase their customer base. ",
      type: "email, retention, conversion",
      img: "https://cdn.pixabay.com/photo/2018/08/03/23/36/marketing-3582974__480.jpg",
      creation_date: "2022-11-11",
      userMail: "adminseeder@admin.com"
    },
    {
      title: "The Top 5 Ways to Use Customer Feedback to Drive Business Growth",
      text: "As a business owner, customer feedback is one of the most valuable tools you have for improving your products and services. By listening to your customers and taking their comments and suggestions into consideration, you can make necessary changes to your business that drive growth and increase customer satisfaction. Here are the top 5 ways to use customer feedback to drive business growth: Identify areas for improvement: By regularly soliciting feedback from your customers, you can identify any pain points or areas of your business that need improvement. This could be anything from the quality of your products to the efficiency of your customer service. By addressing these issues and making changes based on customer feedback, you can improve the overall customer experience and drive growth. Develop new products and services: Customer feedback can also be a valuable source of inspiration for new products and services. By asking customers what they would like to see from your business and incorporating their ideas into your product development process, you can create products and services that are in demand and drive growth. Personalize the customer experience: By listening to customer feedback, you can tailor your products and services to meet the specific needs and preferences of your customers. This personalization can lead to increased customer satisfaction and loyalty, which can ultimately drive business growth. Increase customer loyalty: By actively seeking and responding to customer feedback, you show your customers that you value their opinions and are willing to make changes to improve their experience. This can lead to increased customer loyalty, which can drive growth through repeat business and word-of-mouth referrals. In conclusion, customer feedback is a powerful tool for driving business growth. By regularly soliciting and acting on feedback, you can identify areas for improvement, develop new products and services, personalize the customer experience, and increase customer loyalty. By using customer feedback to drive growth, you can keep your business moving forward and stay ahead of the competition. ",
      type: "retention, ux, ui",
      img: "https://www.impactbnd.com/hubfs/8%20smart%20ways%20to%20collect%20customer%20feedback%20%5Binfographic%5D.jpg",
      creation_date: "2022-11-11",
      userMail: "adminseeder@admin.com"
    },
    {
      title: "The Top 3 Ways to Use Paid Advertising for Business Growth",
      text: "Paid advertising can be a powerful tool for business growth, but it's important to use it wisely. Here are the top three ways to use paid advertising to help your business grow: Targeted advertising: One of the key benefits of paid advertising is the ability to target specific audiences. By using demographics, interests, and location data, you can reach people who are most likely to be interested in your products or services. This can be especially useful for businesses that have a specific customer base in mind, such as a fashion retailer targeting young women or a home improvement company targeting homeowners. Retargeting: Have you ever visited a website and then started seeing ads for that company everywhere you go online? That's retargeting, and it can be an effective way to bring visitors back to your website. By placing a small piece of code on your website, you can track visitors and then serve them targeted ads as they browse the web. This can be a great way to bring back visitors who didn't convert on their first visit and give them another chance to become customers. Social media advertising: Social media platforms like Facebook, Instagram, and LinkedIn offer a wide range of paid advertising options, from sponsored posts to targeted ads. By using social media advertising, you can reach specific audiences based on their interests and behaviors, and you can even set up custom audiences based on your own customer lists. Plus, social media advertising is relatively affordable, making it a great option for businesses on a budget. Overall, paid advertising can be a powerful tool for business growth, but it's important to use it wisely. By targeting specific audiences, retargeting visitors, and using social media advertising, you can reach the people who are most likely to become customers and help your business grow.",
      type: "paid, sem, social",
      img: "https://www.lucushost.com/blog/wp-content/uploads/2019/12/que-es-sem.png",
      creation_date: "2022-11-11",
      userMail: "adminseeder@admin.com"
    },
    {
      title: "The Top 3 Ways to Use Personalization for Business Growth",
      text: "Personalization is a powerful tool for businesses looking to grow and stand out in a crowded market. By tailoring your marketing efforts to individual customers, you can build strong relationships and create a loyal customer base. Here are the top three ways to use personalization for business growth: Targeted email marketing campaigns: Email is a cost-effective way to reach a large audience, but it’s important to avoid sending generic, mass emails that are likely to end up in the trash. Instead, use personalization to create targeted emails that speak directly to the recipient. This could include using their name in the subject line, tailoring the content to their interests or needs, and including relevant recommendations based on their past purchases. Personalized product recommendations: Customers appreciate being offered products that are tailored to their interests and needs. By using data analytics, businesses can create personalized product recommendations for individual customers based on their browsing and purchase history. This can help increase sales and customer satisfaction. Personalized customer service: Personalization doesn’t have to be limited to marketing efforts. By using personalized customer service, businesses can create a more positive customer experience and build stronger relationships. This could include using the customer’s name, remembering their preferences and previous interactions, and offering personalized support and solutions. Overall, personalization is a key element of business growth. By tailoring marketing efforts, product recommendations, and customer service to individual customers, businesses can create a more personalized and satisfying experience for their customers, leading to increased loyalty and growth.",
      type: "ux, ui, conversion",
      img: "https://www.incimages.com/uploaded_files/image/1920x1080/getty_185895589_9706469704500108_79369.jpg",
      creation_date: "2022-11-11",
      userMail: "adminseeder@admin.com"
    }    
  ], {});
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
